CREATE DATABASE IF NOT EXISTS `memory` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'oclock'@'localhost' IDENTIFIED VIA mysql_native_password USING '***';
GRANT USAGE ON *.* TO 'oclock'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `memory`.* TO 'oclock'@'localhost' WITH GRANT OPTION;
